/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertsJSON: typeof import('./src/components/notifications/AlertsJSON.vue')['default']
    JavaScriptCodearea: typeof import('./src/components/textarea/JavaScriptCodearea.vue')['default']
    JSONCodearea: typeof import('./src/components/textarea/JSONCodearea.vue')['default']
  }
}
