/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaixaDeEntradaJson: typeof import('./src/components/CaixaDeEntradaJson.vue')['default']
    CaixaDeSaidaArray: typeof import('./src/components/CaixaDeSaidaArray.vue')['default']
    CardCaixaDeEntrada: typeof import('./src/components/CardCaixaDeEntrada.vue')['default']
    CardCaixaDeSaida: typeof import('./src/components/CardCaixaDeSaida.vue')['default']
    copy: typeof import('./src/components/CardCaixaDeEntrada copy.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    IndexConversor: typeof import('./src/components/IndexConversor.vue')['default']
  }
}
